
# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
identifier = "imprint"
name = "Imprint"
url = "/imprint/"
weight = 50

[main.params]
icon = "section-sign"
newtab = false


[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/steffenaxer"

[social.params]
icon = "brand-linkedin"
